export const FETCH_USER = 'fetch_user'
export const REQUEST_DATA_FETCHING = 'requestDataFetching'
export const FETCHING_DATA_SUCCESS = 'fetchingDataSuccess'
export const FETCHING_DATA_FAIL = 'fetchingDataFail'
export const FETCH_USER_BY_ID = 'fetchUserById'
